version: "2"
services:
  codestopper:
    image: choephixpi/codestopper
    container_name: code-stopper
    hostname: codestopper
    restart: always
    environment:
      - VERBOSE=false
      - MAX_PING_DELTA=900
      - PING_URL=http://gccxpi.duckdns.org/ping/get
      - COMPUTE_ZONE=europe-west3-c
      - COMPUTE_INSTANCE=beast